App:
    Name: DEMOX_ADMINAUTH
    Password: '123456'

Api:
  Host: 0.0.0.0:80
  OpenGinLog: true
  ViewDir : ./view

Log:
  LogName: ./log/api.log
  Level: debug
  OutType: all
  Formatter: txt

Mysql:
  User: root
  Password: "a12346"
  Host: mysql:3306
  DbName: DEMO_ADMINAUTH
  LogFile:
  LogLevel: 4

Redis:
  Addr: redis:6379
  Password: ''
  Db: 0

Jwt:
  Secret: jwtsecret123#$
  # 过期时间 3天
  Exp: 259200

Trace:
  Enable: true
  EndpointUrl: "http://observe:5080/api/default/traces"
  Auth: "Basic cm9vdEBxcS5jb206RFFCRmhVcXRYaVh1MkJtYg=="
  ServerName: "adminsys"
  StreamName:  "adminstream"

Metric:
  Enable: true
  EndpointUrl: "http://observe:5080/api/default/v1/metrics"
  Auth: "Basic cm9vdEBxcS5jb206RFFCRmhVcXRYaVh1MkJtYg=="
  ServerName: "adminsys"
  StreamName: "default"
  Interval: 10 #导出时间间隔 单位秒



